from django.urls import path

from modules import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("overview/", views.fleet_overview, name="fleet_overview"),
    path("set-host/<str:name>/", views.set_host, name="set_host"),
    path("modules/<str:name>/", views.module_detail, name="module_detail"),
    path("shared/<str:name>/", views.shared_detail, name="shared_detail"),
    path("acl/", views.acl_matrix, name="acl_matrix"),
    path("logs/", views.all_logs, name="all_logs"),
    path("xmpp-users/", views.xmpp_users, name="xmpp_users"),
    # API
    path("api/statuses/", views.api_all_statuses, name="api_all_statuses"),
    path("api/logs/", views.api_all_logs, name="api_all_logs"),
    path("api/modules/<str:name>/status/", views.api_status, name="api_status"),
    path("api/modules/<str:name>/start/", views.api_start, name="api_start"),
    path("api/modules/<str:name>/stop/", views.api_stop, name="api_stop"),
    path("api/modules/<str:name>/activate/", views.api_activate, name="api_activate"),
    path("api/modules/<str:name>/deactivate/", views.api_deactivate, name="api_deactivate"),
    path("api/modules/<str:name>/restart/", views.api_restart, name="api_restart"),
    path("api/modules/<str:name>/logs/", views.api_logs, name="api_logs"),
    path("api/modules/<str:name>/log-stats/", views.api_log_stats, name="api_log_stats"),
    path("api/log-stats/", views.api_all_log_stats, name="api_all_log_stats"),
    path("api/modules/<str:name>/config/", views.api_config, name="api_config"),
    path("api/shared/<str:name>/config/", views.api_shared_config, name="api_shared_config"),
    path("api/modules/<str:name>/acl/", views.api_acl, name="api_acl"),
    path("api/acl-matrix/", views.api_acl_matrix, name="api_acl_matrix"),
    path("api/ejabberd/status/", views.api_ejabberd_status, name="api_ejabberd_status"),
    path("api/ejabberd/user/<str:user>/", views.api_ejabberd_user, name="api_ejabberd_user"),
    path("api/ejabberd/user/<str:user>/register/", views.api_ejabberd_user_register, name="api_ejabberd_user_register"),
    path("api/ejabberd/user/<str:user>/change-password/", views.api_ejabberd_user_change_password, name="api_ejabberd_user_change_password"),
    path("api/ejabberd/user/<str:user>/ban/", views.api_ejabberd_user_ban, name="api_ejabberd_user_ban"),
    path("api/ejabberd/user/<str:user>/unban/", views.api_ejabberd_user_unban, name="api_ejabberd_user_unban"),
    path("api/ejabberd/user/<str:user>/unregister/", views.api_ejabberd_user_unregister, name="api_ejabberd_user_unregister"),
    path("api/ejabberd/user/<str:user>/kick/", views.api_ejabberd_user_kick, name="api_ejabberd_user_kick"),
    path("api/ejabberd/users/", views.api_ejabberd_users, name="api_ejabberd_users"),
    path("api/ejabberd-summary/", views.api_ejabberd_summary, name="api_ejabberd_summary"),
    path("api/xmpp-users/", views.api_xmpp_users, name="api_xmpp_users"),
    path("api/xmpp-users/<str:user>/register/", views.api_ejabberd_users_register, name="api_ejabberd_users_register"),
    path("api/xmpp-users/<str:user>/ban/", views.api_ejabberd_users_ban, name="api_ejabberd_users_ban"),
    path("api/xmpp-users/<str:user>/unban/", views.api_ejabberd_users_unban, name="api_ejabberd_users_unban"),
    path("api/xmpp-users/<str:user>/unregister/", views.api_ejabberd_users_unregister, name="api_ejabberd_users_unregister"),
    path("api/xmpp-users/<str:user>/kick/", views.api_ejabberd_users_kick, name="api_ejabberd_users_kick"),
    path("api/comm-user-map/", views.api_comm_user_map, name="api_comm_user_map"),
    path("api/modules/<str:name>/ejabberd/", views.api_module_ejabberd, name="api_module_ejabberd"),
    path("api/modules/<str:name>/ejabberd/register/", views.api_module_ejabberd_register, name="api_module_ejabberd_register"),
    path("api/modules/<str:name>/ejabberd/change-password/", views.api_module_ejabberd_change_password, name="api_module_ejabberd_change_password"),
    path("api/modules/<str:name>/ejabberd/ban/", views.api_module_ejabberd_ban, name="api_module_ejabberd_ban"),
    path("api/modules/<str:name>/ejabberd/unban/", views.api_module_ejabberd_unban, name="api_module_ejabberd_unban"),
    path("api/modules/<str:name>/ejabberd/unregister/", views.api_module_ejabberd_unregister, name="api_module_ejabberd_unregister"),
]
